// <auto-generated />
using System;
using Imobiliare.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Imobiliare.Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("Imobiliare.Entities.Agentie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AfisarePrimaPagina")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriereAgentie")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Nume")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("OrasSelect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PozaAgentie")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("PromotedLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelefonAgentie")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Website")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("OrasSelect");

                    b.ToTable("Agentie", (string)null);
                });

            modelBuilder.Entity("Imobiliare.Entities.Ansamblu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Continut")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<double>("GoogleMarkerCoordinateLat")
                        .HasColumnType("REAL");

                    b.Property<double>("GoogleMarkerCoordinateLong")
                        .HasColumnType("REAL");

                    b.Property<string>("Keywords")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("NumarVizualizari")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrasSelect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Poze")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("UserId")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("OrasSelect");

                    b.HasIndex("UserId");

                    b.ToTable("Ansamblu", (string)null);
                });

            modelBuilder.Entity("Imobiliare.Entities.AuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool>("NotifyAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("AuditTrail", (string)null);
                });

            modelBuilder.Entity("Imobiliare.Entities.BlockedIp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("BlockCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAdaugare")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRegex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TraceBlocking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UpdateBlockCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BlockedIp", (string)null);
                });

            modelBuilder.Entity("Imobiliare.Entities.Cartier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nume")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("OrasId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrasId");

                    b.ToTable("Cartier", (string)null);
                });

            modelBuilder.Entity("Imobiliare.Entities.Constructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descriere")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Nume")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("OrasId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Poza")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Telefon")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Website")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("OrasId");

                    b.ToTable("Constructor", (string)null);
                });

            modelBuilder.Entity("Imobiliare.Entities.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmailTemplateCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HumanReadableEmailIdentifier")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplate", (string)null);
                });

            modelBuilder.Entity("Imobiliare.Entities.FavoriteAnuntItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FavoritesID")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("ImobilId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImobilId");

                    b.ToTable("FavoriteAnuntItems");
                });

            modelBuilder.Entity("Imobiliare.Entities.Imobil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AerConditionat")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CT")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cartier_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(40)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ContactTelefon")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime>("DataAdaugare")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAdaugareInitiala")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAprobare")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Decomandat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("Etaj")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Finisat")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Garaj")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GoogleMarkerCoordinateLat")
                        .HasColumnType("REAL");

                    b.Property<double>("GoogleMarkerCoordinateLong")
                        .HasColumnType("REAL");

                    b.Property<int?>("Judet_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkExtern")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool>("LocInPivnita")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LocParcare")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Negociabil")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NrBai")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NrBalcoane")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumarCamere")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumarTotalEtaje")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumarVizualizari")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObservatiiAdmin")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("Oras_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Poze")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PromotedLevel")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("StareAprobare")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Strada")
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("Suprafata")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipOfertaGen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipProprietate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipVanzator")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("UserId")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("Valabilitate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VechimeImobil")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Cartier_Id");

                    b.HasIndex("Judet_Id");

                    b.HasIndex("Oras_Id");

                    b.HasIndex("UserId");

                    b.ToTable("Imobil", (string)null);
                });

            modelBuilder.Entity("Imobiliare.Entities.Judet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoordinateGps")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Descriere")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Nume")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("PrescurtareAuto")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("Judet", (string)null);
                });

            modelBuilder.Entity("Imobiliare.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Level")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Logger")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Message")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Thread")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("Log", (string)null);
                });

            modelBuilder.Entity("Imobiliare.Entities.Mesaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categorie")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CitireDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Continut")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromUserId")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("ImobilId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToUserId")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("UserContactFormId")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ImobilId");

                    b.HasIndex("ToUserId");

                    b.HasIndex("UserContactFormId");

                    b.ToTable("Mesaj", (string)null);
                });

            modelBuilder.Entity("Imobiliare.Entities.Oras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodPostal")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("CoordinateGps")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("DescriereLocalitate")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("JudetId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LocalitateMica")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nume")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool>("ResedintaJudet")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JudetId");

                    b.ToTable("Oras", (string)null);
                });

            modelBuilder.Entity("Imobiliare.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("AddressLine2")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("State")
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Imobiliare.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImobilId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImobilId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Imobiliare.Entities.RaportActivitate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnsambluriAdaugateCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnunturiByAdminCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnunturiByUsersCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuditTrailsCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalEmail")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("GenerareRaportTime")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool>("IsFakeEmailManager")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastConsideredHoursCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceiversCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionStartedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionStartedDistinctCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StiriAdaugateCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UseriCreatiCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RaportActivitate", (string)null);
                });

            modelBuilder.Entity("Imobiliare.Entities.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImobilId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShoppingCartId")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("ImobilId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("Imobiliare.Entities.Stire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AfiseazaPrimaPagina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieStire")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Continut")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Keywords")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("LinkExtern")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("MetaDescription")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("NumarVizualizari")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrasSelect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Poze")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("TitluUrl")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("UserId")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Stire", (string)null);
                });

            modelBuilder.Entity("Imobiliare.Entities.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoApproveAnunturi")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoSendAnuntExpiratEmails")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CapchaEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultPageSizeAdminPageAnunturi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultPageSizeAdminPageUsers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultPageSizeMainPages")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogsRetrieveNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDbSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyAdminByEmailWhenUserChangedAnuntByEmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyAdminByEmailWhenUserContactsAnotherUser")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseFakeEmailManager")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("Imobiliare.Entities.UserProfile", b =>
                {
                    b.Property<string>("Id")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool>("AbonatLaNewsLetter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgentieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ConfirmationToken")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("ConstructorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriereAgent")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Flags")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool>("IsAgentieAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("NumeAgentieImobiliara")
                        .HasMaxLength(40)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("NumeComplet")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("PasswordHash")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("PhoneNumber")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Picture")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool>("ReceiveAdminReports")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RestrictionatPrimireEmail")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("StareUser")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipVanzator")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrustedUser")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UserCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("AgentieId");

                    b.HasIndex("ConstructorId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ClaimValue")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ClaimValue")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ProviderKey")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ProviderDisplayName")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("RoleId")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("LoginProvider")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Name")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Value")
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Imobiliare.Entities.Agentie", b =>
                {
                    b.HasOne("Imobiliare.Entities.Oras", "Oras")
                        .WithMany()
                        .HasForeignKey("OrasSelect")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Oras");
                });

            modelBuilder.Entity("Imobiliare.Entities.Ansamblu", b =>
                {
                    b.HasOne("Imobiliare.Entities.Oras", "Oras")
                        .WithMany()
                        .HasForeignKey("OrasSelect")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Imobiliare.Entities.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Oras");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Imobiliare.Entities.Cartier", b =>
                {
                    b.HasOne("Imobiliare.Entities.Oras", "Oras")
                        .WithMany()
                        .HasForeignKey("OrasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Oras");
                });

            modelBuilder.Entity("Imobiliare.Entities.Constructor", b =>
                {
                    b.HasOne("Imobiliare.Entities.Oras", "Oras")
                        .WithMany()
                        .HasForeignKey("OrasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Oras");
                });

            modelBuilder.Entity("Imobiliare.Entities.FavoriteAnuntItem", b =>
                {
                    b.HasOne("Imobiliare.Entities.Imobil", "Imobil")
                        .WithMany()
                        .HasForeignKey("ImobilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Imobil");
                });

            modelBuilder.Entity("Imobiliare.Entities.Imobil", b =>
                {
                    b.HasOne("Imobiliare.Entities.Cartier", "Cartier")
                        .WithMany()
                        .HasForeignKey("Cartier_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Imobiliare.Entities.Judet", "Judet")
                        .WithMany()
                        .HasForeignKey("Judet_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Imobiliare.Entities.Oras", "Oras")
                        .WithMany()
                        .HasForeignKey("Oras_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Imobiliare.Entities.UserProfile", "UserProfile")
                        .WithMany("Anunturi")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cartier");

                    b.Navigation("Judet");

                    b.Navigation("Oras");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Imobiliare.Entities.Mesaj", b =>
                {
                    b.HasOne("Imobiliare.Entities.UserProfile", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Imobiliare.Entities.Imobil", "Imobil")
                        .WithMany()
                        .HasForeignKey("ImobilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Imobiliare.Entities.UserProfile", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Imobiliare.Entities.UserProfile", "UserContactForm")
                        .WithMany()
                        .HasForeignKey("UserContactFormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("Imobil");

                    b.Navigation("ToUser");

                    b.Navigation("UserContactForm");
                });

            modelBuilder.Entity("Imobiliare.Entities.Oras", b =>
                {
                    b.HasOne("Imobiliare.Entities.Judet", "Judet")
                        .WithMany()
                        .HasForeignKey("JudetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Judet");
                });

            modelBuilder.Entity("Imobiliare.Entities.OrderDetail", b =>
                {
                    b.HasOne("Imobiliare.Entities.Imobil", "Imobil")
                        .WithMany()
                        .HasForeignKey("ImobilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Imobiliare.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Imobil");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Imobiliare.Entities.ShoppingCartItem", b =>
                {
                    b.HasOne("Imobiliare.Entities.Imobil", "Imobil")
                        .WithMany()
                        .HasForeignKey("ImobilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Imobil");
                });

            modelBuilder.Entity("Imobiliare.Entities.Stire", b =>
                {
                    b.HasOne("Imobiliare.Entities.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Imobiliare.Entities.UserProfile", b =>
                {
                    b.HasOne("Imobiliare.Entities.Agentie", "Agentie")
                        .WithMany("AgentieImobiliaraUserProfiles")
                        .HasForeignKey("AgentieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Imobiliare.Entities.Constructor", "Constructor")
                        .WithMany("ConstructorUserProfiles")
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Agentie");

                    b.Navigation("Constructor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Imobiliare.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Imobiliare.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Imobiliare.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Imobiliare.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Imobiliare.Entities.Agentie", b =>
                {
                    b.Navigation("AgentieImobiliaraUserProfiles");
                });

            modelBuilder.Entity("Imobiliare.Entities.Constructor", b =>
                {
                    b.Navigation("ConstructorUserProfiles");
                });

            modelBuilder.Entity("Imobiliare.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Imobiliare.Entities.UserProfile", b =>
                {
                    b.Navigation("Anunturi");
                });
#pragma warning restore 612, 618
        }
    }
}
