// <auto-generated />
using System;
using CoreTestApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreTestApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230403094739_AddFavoritesItems")]
    partial class AddFavoritesItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreTestApp.Models.FavoriteAnuntItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FavoritesID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImobilId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImobilId");

                    b.ToTable("FavoriteAnuntItems");
                });

            modelBuilder.Entity("CoreTestApp.Models.Imobil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AerConditionat")
                        .HasColumnType("bit");

                    b.Property<bool>("CT")
                        .HasColumnType("bit");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ContactTelefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAdaugare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataAdaugareInitiala")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataAprobare")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Decomandat")
                        .HasColumnType("bit");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Etaj")
                        .HasColumnType("int");

                    b.Property<bool>("Finisat")
                        .HasColumnType("bit");

                    b.Property<bool>("Garaj")
                        .HasColumnType("bit");

                    b.Property<double>("GoogleMarkerCoordinateLat")
                        .HasColumnType("float");

                    b.Property<double>("GoogleMarkerCoordinateLong")
                        .HasColumnType("float");

                    b.Property<string>("LinkExtern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LocInPivnita")
                        .HasColumnType("bit");

                    b.Property<bool>("LocParcare")
                        .HasColumnType("bit");

                    b.Property<bool>("Negociabil")
                        .HasColumnType("bit");

                    b.Property<int?>("NrBai")
                        .HasColumnType("int");

                    b.Property<int?>("NrBalcoane")
                        .HasColumnType("int");

                    b.Property<int?>("NumarCamere")
                        .HasColumnType("int");

                    b.Property<int>("NumarTotalEtaje")
                        .HasColumnType("int");

                    b.Property<int>("NumarVizualizari")
                        .HasColumnType("int");

                    b.Property<string>("ObservatiiAdmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poze")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Strada")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Suprafata")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Valabilitate")
                        .HasColumnType("int");

                    b.Property<int?>("VechimeImobil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Imobils");
                });

            modelBuilder.Entity("CoreTestApp.Models.FavoriteAnuntItem", b =>
                {
                    b.HasOne("CoreTestApp.Models.Imobil", "Imobil")
                        .WithMany()
                        .HasForeignKey("ImobilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imobil");
                });
#pragma warning restore 612, 618
        }
    }
}
